language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

install:
  # install php packages required for running a web server from drush on php 5.3
  - travis_retry composer install --no-interaction --prefer-source

  # install node.js packages required for various tasks (bower, grunt, etc)
  - npm install

  # install bower libraries (AngularJS, jQuery, Bootstrap, etc)
  - bower install

before_script:
  # get Google's closure compiler for JavaScript
  - wget http://dl.google.com/closure-compiler/compiler-latest.zip
  - tar -xvzf compiler-latest.zip

script:
  # create new database
  - mysql -e 'create database begborrowshare'

  # build, deploy, run all the tests
  - export CLOSURE_PATH=$(pwd)
  - grunt
