language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq ant

install:
  # install php packages required for running a web server from drush on php 5.3
  - travis_retry composer install --no-interaction --prefer-source

  # install node.js packages required for various tasks (bower, grunt, etc)
  - npm install --silent

  # install bower libraries (AngularJS, jQuery, Bootstrap, etc)
  - bower install --silent

  # ...install and build Google's closure compiler
  - git clone --depth=50 --branch=master git://github.com/google/closure-compiler.git
  - cd closure-compiler
  - ant jar

script:
  - export CLOSURE_PATH=$(pwd)/closure-compiler

  # create new database
  - mysql -e 'create database begborrowshare'

  # build and deploy...
  - grunt

  # start a web server on port 8080, run in the background; wait for initialization
  - php artisan serve &
  - until netstat -an 2>/dev/null | grep '8080.*LISTEN'; do true; done
