language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

mysql:
  database: begborrowshare
  username: root
  encoding: utf8

env: 
	- CLOSURE_PATH=$(pwd)/closure-compiler

install:
  # install php packages required for running a web server from drush on php 5.3
  - travis_retry composer install --no-interaction --prefer-source

  # install node.js packages required for various tasks (bower, grunt, etc)
  - npm install --silent

  # install bower libraries (AngularJS, jQuery, Bootstrap, etc)
  - bower install --silent

  # install ant so we can...
  - sudo apt-get -u install ant

  # ...install and build Google's closure compiler
  - mkdir closure-compiler
  - cd closure-compiler
  - git clone --depth=50 --branch=master git@github.com:google/closure-compiler.git
  - ant jar

before_script:
	# update all the tools
  - composer self-update
  - npm update --silent
  - bower update --silent

script:
  # create new database
  - mysql -e 'create database begborrowshare'

  # build and deploy...
  - grunt

  # start a web server on port 8080, run in the background; wait for initialization
  - php artisan serve &
  - until netstat -an 2>/dev/null | grep '8080.*LISTEN'; do true; done

notifications:
    on_success: never
    on_failure: always